# this docker compose exists only for dev purposes
version: '3'
services:
  memcachedb:
    image: redis:latest
    ports:
      - 6379:6379
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: recipiece
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: recipiece
    ports:
      - 5432:5432
