FROM node:alpine

ENV RCP_ENV_NAME docker

WORKDIR /rcp-memcache
COPY memcache memcache/
COPY node-common node-common/
COPY environment environment/
COPY tsconfig.prod.json .

RUN npm i -g typescript ts-node
RUN cd common && yarn build && yarn link

ENTRYPOINT cd memcache && yarn link recipiece-common && yarn run-dev
