FROM node:alpine

WORKDIR /rcp-auth
COPY auth auth/
COPY common common/
COPY tsconfig.json .

RUN npm i -g typescript ts-node
RUN cd common && yarn build && yarn link

ENV RCP_INTERNAL_USER="aW50ZXJuYWxAcmVjaXBpZWNlLm9yZy5pbnRlcm5hbEByZWNpcGllY2Uub3JnLjA="

ENTRYPOINT cd auth && yarn link recipiece-common && yarn run-dev
