FROM node:alpine

ENV RCP_ENV_NAME docker

WORKDIR /rcp-recipes
COPY recipes recipes/
COPY node-common node-common/
COPY environment environment/
COPY tsconfig.json .

RUN npm i -g typescript ts-node
RUN cd node-common && yarn build && yarn link

ENTRYPOINT cd recipes && yarn link recipiece-common && yarn run-dev
