FROM node:alpine

WORKDIR /rcp-memcache
COPY memcache memcache/
COPY common common/
COPY tsconfig.json .

RUN npm i -g typescript nodemon ts-node
RUN cd common && yarn build && yarn link

ENTRYPOINT cd memcache && yarn link recipiece-common && nodemon src/app.ts
