FROM node:alpine

WORKDIR /rcp-database
COPY database database/
COPY common common/
COPY tsconfig.json .

RUN npm i -g typescript nodemon ts-node
RUN cd common && yarn build && yarn link

ENTRYPOINT cd database && yarn link recipiece-common && nodemon src/app.ts
