FROM node:alpine

WORKDIR /rcp-auth
COPY auth auth/
COPY common common/
COPY tsconfig.json .

RUN npm i -g typescript nodemon ts-node
RUN cd common && yarn build && yarn link

ENTRYPOINT cd auth && yarn link recipiece-common && nodemon src/app.ts
